use crate::stdlib::{EventType, StdLib};
use serde_json::json;
use std::collections::{HashMap, HashSet};
use std::fs;
use std::io::Write;
use std::path::PathBuf;

pub struct DataPack {
    pub namespace: String,
    pub description: String,
    pub output_dir: PathBuf,
    pub functions: HashMap<String, Vec<String>>,
    pub tags: HashMap<String, Vec<String>>,
    pub advancements: HashMap<String, String>,
    pub loot_tables: HashMap<String, String>,
    pub recipes: HashMap<String, String>,
    pub predicates: HashMap<String, String>,
    pub item_modifiers: HashMap<String, String>,
    pub pack_format: u8,
    pub stdlib: StdLib,
    pub used_objectives: HashSet<String>,
}

impl DataPack {
    pub fn new(namespace: String, output_dir: PathBuf) -> Self {
        Self {
            namespace,
            description: "Generated by Cobble".to_string(),
            output_dir,
            functions: HashMap::new(),
            tags: HashMap::new(),
            advancements: HashMap::new(),
            loot_tables: HashMap::new(),
            recipes: HashMap::new(),
            predicates: HashMap::new(),
            item_modifiers: HashMap::new(),
            pack_format: 88, // Minecraft 1.21.9+ format (recommended)
            stdlib: StdLib::new(),
            used_objectives: HashSet::new(),
        }
    }

    pub fn set_description(&mut self, desc: String) {
        self.description = desc;
    }

    pub fn set_pack_format(&mut self, format: u8) {
        self.pack_format = format;
    }

    pub fn add_function(&mut self, name: String, commands: Vec<String>) {
        self.functions.insert(name, commands);
    }

    pub fn track_objective(&mut self, objective: &str) {
        self.used_objectives.insert(objective.to_string());
    }

    pub fn ensure_init_function(&mut self) {
        // Get or create the init function from load event handlers
        let load_handlers = self.stdlib.get_event_handlers(&EventType::Load);

        if let Some(init_func_name) = load_handlers.first() {
            // Add objectives to the beginning of the load function
            if let Some(commands) = self.functions.get_mut(init_func_name) {
                // Collect objectives that aren't already in the function
                let mut new_objectives = Vec::new();
                for objective in &self.used_objectives {
                    let obj_cmd = format!("scoreboard objectives add {} dummy", objective);
                    // Only add if not already present
                    if !commands.contains(&obj_cmd) {
                        new_objectives.push(obj_cmd);
                    }
                }

                // Prepend new objectives to existing commands
                if !new_objectives.is_empty() {
                    new_objectives.extend(commands.clone());
                    *commands = new_objectives;
                }
            }
        } else if !self.used_objectives.is_empty() {
            // No load handler exists, create a default init function
            let mut commands = Vec::new();
            for objective in &self.used_objectives {
                commands.push(format!("scoreboard objectives add {} dummy", objective));
            }

            self.functions.insert("_cobble_init".to_string(), commands);
            self.stdlib
                .add_event_listener(EventType::Load, "_cobble_init".to_string());
        }
    }

    pub fn add_tag(&mut self, tag_name: String, functions: Vec<String>) {
        self.tags.insert(tag_name, functions);
    }

    pub fn add_advancement(&mut self, name: String, json: String) {
        self.advancements.insert(name, json);
    }

    pub fn add_loot_table(&mut self, name: String, json: String) {
        self.loot_tables.insert(name, json);
    }

    pub fn add_recipe(&mut self, name: String, json: String) {
        self.recipes.insert(name, json);
    }

    pub fn add_predicate(&mut self, name: String, json: String) {
        self.predicates.insert(name, json);
    }

    pub fn add_item_modifier(&mut self, name: String, json: String) {
        self.item_modifiers.insert(name, json);
    }

    pub fn write(&self) -> std::io::Result<()> {
        let data_dir = self.output_dir.join("data");
        let namespace_dir = data_dir.join(&self.namespace);
        let functions_dir = namespace_dir.join("function");
        let minecraft_tags_dir = self
            .output_dir
            .join("data")
            .join("minecraft")
            .join("tags")
            .join("function");
        let tags_dir = namespace_dir.join("tags").join("function");

        fs::create_dir_all(&functions_dir)?;
        fs::create_dir_all(&tags_dir)?;

        // Write pack.mcmeta
        self.write_pack_mcmeta()?;

        // Write all functions
        for (name, commands) in &self.functions {
            let file_path = functions_dir.join(format!("{}.mcfunction", name));
            let mut file = fs::File::create(file_path)?;
            for command in commands {
                writeln!(file, "{}", command)?;
            }
        }

        // Write tags from stdlib
        let stdlib_tags = self.stdlib.generate_tags(&self.namespace);
        for (tag_name, functions) in stdlib_tags {
            let tag_file = if tag_name.starts_with("minecraft:") {
                // Special minecraft tags go in minecraft namespace
                fs::create_dir_all(&minecraft_tags_dir)?;
                let tag_name = tag_name.strip_prefix("minecraft:").unwrap();
                minecraft_tags_dir.join(format!("{}.json", tag_name))
            } else {
                tags_dir.join(format!("{}.json", tag_name))
            };

            let tag_content = json!({
                "values": functions
            });

            let mut file = fs::File::create(tag_file)?;
            writeln!(
                file,
                "{}",
                serde_json::to_string_pretty(&tag_content).unwrap()
            )?;
        }

        // Write advancements
        if !self.advancements.is_empty() {
            let advancements_dir = namespace_dir.join("advancement");
            fs::create_dir_all(&advancements_dir)?;
            for (name, json) in &self.advancements {
                let file_path = advancements_dir.join(format!("{}.json", name));
                fs::write(file_path, json)?;
            }
        }

        // Write loot tables
        if !self.loot_tables.is_empty() {
            let loot_tables_dir = namespace_dir.join("loot_table");
            fs::create_dir_all(&loot_tables_dir)?;
            for (name, json) in &self.loot_tables {
                let file_path = loot_tables_dir.join(format!("{}.json", name));
                fs::write(file_path, json)?;
            }
        }

        // Write recipes
        if !self.recipes.is_empty() {
            let recipes_dir = namespace_dir.join("recipe");
            fs::create_dir_all(&recipes_dir)?;
            for (name, json) in &self.recipes {
                let file_path = recipes_dir.join(format!("{}.json", name));
                fs::write(file_path, json)?;
            }
        }

        // Write predicates
        if !self.predicates.is_empty() {
            let predicates_dir = namespace_dir.join("predicate");
            fs::create_dir_all(&predicates_dir)?;
            for (name, json) in &self.predicates {
                let file_path = predicates_dir.join(format!("{}.json", name));
                fs::write(file_path, json)?;
            }
        }

        // Write item modifiers
        if !self.item_modifiers.is_empty() {
            let item_modifiers_dir = namespace_dir.join("item_modifier");
            fs::create_dir_all(&item_modifiers_dir)?;
            for (name, json) in &self.item_modifiers {
                let file_path = item_modifiers_dir.join(format!("{}.json", name));
                fs::write(file_path, json)?;
            }
        }

        Ok(())
    }

    fn write_pack_mcmeta(&self) -> std::io::Result<()> {
        let mcmeta_path = self.output_dir.join("pack.mcmeta");
        let mcmeta_content = json!({
            "pack": {
                "pack_format": self.pack_format,
                "description": self.description
            }
        });

        let mut file = fs::File::create(mcmeta_path)?;
        writeln!(
            file,
            "{}",
            serde_json::to_string_pretty(&mcmeta_content).unwrap()
        )?;
        Ok(())
    }
}
