"use client";

import {
  AlertTriangle,
  BookOpen,
  Braces,
  CheckCircle2,
  Clipboard,
  Code2,
  Download,
  FileCode2,
  FileJson,
  Files,
  Hammer,
  House,
  Loader2,
  Package,
  Play,
  RefreshCcw,
  Terminal,
  WandSparkles
} from "lucide-react";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import type { UIEvent } from "react";
import { createStoredZip, isDataPackZipFile } from "@/lib/datapackZip";
import { GitHubMark } from "./BrandIcons";
import { HighlightedCode } from "./SyntaxHighlighter";
import type { HighlightLanguage } from "./SyntaxHighlighter";

type CompileFile = {
  path: string;
  kind: string;
  content: string;
};

type CompileSummary = {
  namespace: string;
  pack_format: string;
  minecraft_version: string;
  function_count: number;
  command_count: number;
  resource_count: number;
  file_count: number;
};

type CompileResult = {
  ok: boolean;
  files: CompileFile[];
  diagnostics: string[];
  summary: CompileSummary;
};

type WasmModule = {
  default: (
    moduleOrPath?:
      | { module_or_path: RequestInfo | URL | Response | BufferSource | WebAssembly.Module }
      | RequestInfo
      | URL
      | Response
      | BufferSource
      | WebAssembly.Module
  ) => Promise<unknown>;
  compile_cobble: (
    source: string,
    namespace?: string,
    description?: string
  ) => unknown;
};

type OutputView = "functions" | "resources" | "metadata" | "manifest" | "diagnostics";

type Example = {
  name: string;
  namespace: string;
  source: string;
};

const examples: Example[] = [
  {
    name: "Hello World",
    namespace: "demo",
    source: `def on_load():
    /tellraw @a {"text":"Cobble demo loaded","color":"green"}
    /scoreboard objectives add demo dummy
    reward_player()

def reward_player():
    /give @p minecraft:diamond 1
    /title @p title {"text":"Reward unlocked","color":"aqua"}`
  },
  {
    name: "Stdlib Events",
    namespace: "events_demo",
    source: `import stdlib
from stdlib import event

def load():
    /tellraw @a {"text":"Events ready","color":"green"}

def tick():
    /execute as @a[scores={demo=1..}] run title @s actionbar {"text":"Running","color":"yellow"}

stdlib.addEventListener(event.LOAD, load)
stdlib.addEventListener(event.TICK, tick)`
  },
  {
    name: "Inventory Components",
    namespace: "inventory_demo",
    source: `def kit(player):
    /give {player} minecraft:diamond_sword[minecraft:custom_name='{"text":"Cobble Blade","color":"aqua"}'] 1
    /give {player} minecraft:apple 8

def on_load():
    kit("@p")`
  },
  {
    name: "Resources",
    namespace: "resource_demo",
    source: `datapack.function_tag("minecraft:load", ["resource_demo:on_load"])
datapack.predicate("checks/always", {
    "condition": "minecraft:random_chance",
    "chance": 1
})
datapack.dialog("notice", {
    "type": "minecraft:notice",
    "title": {"text": "Resource demo"}
})

def on_load():
    /say resources ready`
  },
  {
    name: "Validation Focus",
    namespace: "validation_demo",
    source: `def commands():
    /dialog show @p validation_demo:notice
    /fetchprofile @p
    /return run say returned
    /version
    /waypoint list @a`
  }
];

const outputViews: Array<{
  id: OutputView;
  label: string;
  icon: typeof FileCode2;
}> = [
  { id: "functions", label: "Functions", icon: FileCode2 },
  { id: "resources", label: "Resources", icon: Files },
  { id: "metadata", label: "Metadata", icon: Braces },
  { id: "manifest", label: "Manifest", icon: FileJson },
  { id: "diagnostics", label: "Diagnostics", icon: AlertTriangle }
];

const description = "Generated by Cobble Web Demo";
const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

export function CobbleDemo() {
  const [selectedExample, setSelectedExample] = useState(0);
  const [source, setSource] = useState(examples[0].source);
  const [namespace, setNamespace] = useState(examples[0].namespace);
  const [result, setResult] = useState<CompileResult | null>(null);
  const [activePath, setActivePath] = useState("");
  const [activeView, setActiveView] = useState<OutputView>("functions");
  const [wasm, setWasm] = useState<WasmModule | null>(null);
  const [status, setStatus] = useState<"loading" | "ready" | "compiling" | "error">(
    "loading"
  );
  const [copied, setCopied] = useState<"file" | null>(null);
  const editorHighlightRef = useRef<HTMLPreElement>(null);

  useEffect(() => {
    let active = true;

    async function loadWasm() {
      try {
        const mod = (await import("@/src/wasm/pkg/cobble_web_wasm.js")) as WasmModule;
        await mod.default({ module_or_path: `${basePath}/wasm/cobble_web_wasm_bg.wasm` });
        if (active) {
          setWasm(mod);
          setStatus("ready");
        }
      } catch (error) {
        if (active) {
          setStatus("error");
          setResult({
            ok: false,
            files: [],
            diagnostics: [error instanceof Error ? error.message : String(error)],
            summary: emptySummary(namespace)
          });
        }
      }
    }

    loadWasm();
    return () => {
      active = false;
    };
  }, []);

  useEffect(() => {
    if (!wasm) {
      return;
    }
    compile();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [wasm]);

  const visibleFiles = useMemo(() => {
    if (!result?.ok || activeView === "diagnostics") {
      return [];
    }
    return result.files.filter((file) => fileMatchesView(file, activeView));
  }, [activeView, result]);

  useEffect(() => {
    if (!result?.ok || activeView === "diagnostics") {
      return;
    }
    if (!visibleFiles.some((file) => file.path === activePath)) {
      setActivePath(defaultActivePath(result.files, activeView));
    }
  }, [activePath, activeView, result, visibleFiles]);

  const activeFile = useMemo(() => {
    if (!result?.ok || activeView === "diagnostics") {
      return null;
    }
    return visibleFiles.find((file) => file.path === activePath) ?? visibleFiles[0] ?? null;
  }, [activePath, activeView, result, visibleFiles]);

  const diagnostics = result?.diagnostics.length
    ? result.diagnostics
    : result?.ok
      ? ["No diagnostics."]
      : ["Loading Cobble WASM compiler..."];

  function compile() {
    if (!wasm) {
      return;
    }

    setStatus("compiling");
    setCopied(null);

    window.setTimeout(() => {
      const compiled = wasm.compile_cobble(source, namespace, description) as CompileResult;
      setResult(compiled);
      setStatus(compiled.ok ? "ready" : "error");
      const nextView = compiled.ok ? activeView : "diagnostics";
      setActiveView(nextView);
      setActivePath(defaultActivePath(compiled.files, nextView));
    }, 0);
  }

  function applyExample(index: number) {
    const example = examples[index];
    setSelectedExample(index);
    setSource(example.source);
    setNamespace(example.namespace);
    setCopied(null);
  }

  async function copyActiveFile() {
    if (!activeFile) {
      return;
    }
    await navigator.clipboard.writeText(activeFile.content);
    setCopied("file");
    window.setTimeout(() => setCopied(null), 1600);
  }

  function downloadActiveFile() {
    if (!activeFile) {
      return;
    }
    downloadText(activeFile.content, downloadNameForPath(activeFile.path));
  }

  function downloadDataPackZip() {
    if (!result?.ok) {
      return;
    }
    const zipFiles = result.files.filter(isDataPackZipFile);
    if (zipFiles.length === 0) {
      return;
    }
    const blob = createStoredZip(zipFiles);
    downloadBlob(blob, `${result.summary.namespace}.zip`);
  }

  function syncEditorScroll(event: UIEvent<HTMLTextAreaElement>) {
    const highlight = editorHighlightRef.current;
    if (!highlight) {
      return;
    }
    highlight.scrollTop = event.currentTarget.scrollTop;
    highlight.scrollLeft = event.currentTarget.scrollLeft;
  }

  return (
    <main>
      <section className="demo-shell">
        <img
          className="hero-image"
          src={`${basePath}/cobble-workshop.jpg`}
          alt=""
        />
        <div className="hero-scrim" />

        <nav className="topbar" aria-label="Primary">
          <Link className="brand" href="/">
            <span className="brand-mark">C</span>
            <span>Cobble</span>
          </Link>
          <div className="nav-actions">
            <Link className="nav-link" href="/">
              <House size={16} />
              <span>Home</span>
            </Link>
            <a className="nav-link" href="https://docs.rs/cobble-lang/latest/cobble/">
              <BookOpen size={16} />
              <span>Docs</span>
            </a>
            <a className="nav-link" href="https://github.com/deveworld/cobble">
              <GitHubMark width={16} height={16} />
              <span>GitHub</span>
            </a>
          </div>
        </nav>

        <div className="hero-copy">
          <p className="eyebrow">Minecraft Java Edition 26.1.2 · Pack Format 101.1</p>
          <h1>Cobble</h1>
          <p>
            A Python-like language that compiles into Minecraft data pack functions.
          </p>
        </div>

        <section className="workbench" aria-label="Cobble compiler demo">
          <div className="panel editor-panel">
            <div className="panel-toolbar">
              <div className="toolbar-title">
                <Code2 size={18} />
                <span>demo.cbl</span>
              </div>
              <div className="toolbar-actions">
                <label className="select-field">
                  <span>sample</span>
                  <select
                    value={selectedExample}
                    onChange={(event) => applyExample(Number(event.target.value))}
                  >
                    {examples.map((example, index) => (
                      <option key={example.name} value={index}>
                        {example.name}
                      </option>
                    ))}
                  </select>
                </label>
                <label className="namespace-field">
                  <span>namespace</span>
                  <input
                    value={namespace}
                    onChange={(event) => setNamespace(event.target.value)}
                    spellCheck={false}
                  />
                </label>
                <button
                  className="icon-button"
                  type="button"
                  onClick={() => applyExample(selectedExample)}
                  title="Reset source"
                >
                  <RefreshCcw size={17} />
                </button>
                <button
                  className="command-button"
                  type="button"
                  onClick={compile}
                  disabled={!wasm || status === "compiling"}
                >
                  {status === "compiling" ? <Loader2 className="spin" size={17} /> : <Play size={17} />}
                  <span>Compile</span>
                </button>
              </div>
            </div>

            <div className="editor-stack">
              <pre className="editor-highlight" ref={editorHighlightRef} aria-hidden="true">
                <code>
                  <HighlightedCode code={source} language="cobble" />
                </code>
              </pre>
              <textarea
                className="source-editor"
                aria-label="Cobble source"
                value={source}
                onChange={(event) => setSource(event.target.value)}
                onScroll={syncEditorScroll}
                spellCheck={false}
              />
            </div>
          </div>

          <div className="panel output-panel">
            <div className="panel-toolbar">
              <div className="toolbar-title">
                <Terminal size={18} />
                <span>{activeView === "diagnostics" ? "diagnostics" : activeFile?.path ?? "output"}</span>
              </div>
              <div className="toolbar-actions output-actions">
                <button
                  className="secondary-button"
                  type="button"
                  onClick={copyActiveFile}
                  disabled={!activeFile}
                  title="Copy selected file"
                >
                  {copied === "file" ? <CheckCircle2 size={17} /> : <Clipboard size={17} />}
                  <span>Copy</span>
                </button>
                <button
                  className="secondary-button"
                  type="button"
                  onClick={downloadActiveFile}
                  disabled={!activeFile}
                  title="Download selected file"
                >
                  <Download size={17} />
                  <span>File</span>
                </button>
                <button
                  className="command-button"
                  type="button"
                  onClick={downloadDataPackZip}
                  disabled={!result?.ok}
                  title="Download data pack ZIP"
                >
                  <Package size={17} />
                  <span>ZIP</span>
                </button>
              </div>
            </div>

            <StatusStrip result={result} status={status} />

            <div className="view-tabs" role="tablist" aria-label="Output views">
              {outputViews.map((view) => {
                const Icon = view.icon;
                return (
                  <button
                    key={view.id}
                    type="button"
                    onClick={() => setActiveView(view.id)}
                    className={view.id === activeView ? "selected" : ""}
                  >
                    <Icon size={14} />
                    <span>{view.label}</span>
                  </button>
                );
              })}
            </div>

            {activeView === "diagnostics" || !result?.ok ? (
              <pre className="diagnostics">{diagnostics.join("\n")}</pre>
            ) : (
              <>
                <div className="file-tabs" role="tablist" aria-label="Generated files">
                  {visibleFiles.map((file) => (
                    <button
                      key={file.path}
                      type="button"
                      onClick={() => setActivePath(file.path)}
                      className={file.path === activeFile?.path ? "selected" : ""}
                      title={file.path}
                    >
                      <FileIcon file={file} />
                      <span>{file.path}</span>
                    </button>
                  ))}
                </div>
                {activeFile ? (
                  <pre className="output-code">
                    <code>
                      <HighlightedCode
                        code={activeFile.content}
                        language={languageForFile(activeFile)}
                      />
                    </code>
                  </pre>
                ) : (
                  <div className="output-empty">No generated files in this view.</div>
                )}
              </>
            )}
          </div>
        </section>
      </section>

      <section className="details-band">
        <div className="detail">
          <WandSparkles size={20} />
          <strong>Browser WASM</strong>
          <span>Rust parser and transpiler run client-side.</span>
        </div>
        <div className="detail">
          <Hammer size={20} />
          <strong>Real output</strong>
          <span>Generated files mirror Cobble data pack paths.</span>
        </div>
        <div className="detail">
          <Braces size={20} />
          <strong>Build manifest</strong>
          <span>Output includes source maps and generated resource metadata.</span>
        </div>
      </section>
    </main>
  );
}

function StatusStrip({
  result,
  status
}: {
  result: CompileResult | null;
  status: "loading" | "ready" | "compiling" | "error";
}) {
  if (!result || status === "loading") {
    return (
      <div className="status-strip pending">
        <Loader2 className="spin" size={16} />
        <span>Loading compiler</span>
      </div>
    );
  }

  if (!result.ok) {
    return (
      <div className="status-strip failed">
        <span>{result.diagnostics.length} diagnostic</span>
      </div>
    );
  }

  return (
    <div className="status-strip">
      <span>{result.summary.function_count} functions</span>
      <span>{result.summary.command_count} commands</span>
      <span>{result.summary.resource_count} resources</span>
      <span>{result.summary.file_count} files</span>
      <span>pack {result.summary.pack_format}</span>
    </div>
  );
}

function FileIcon({ file }: { file: CompileFile }) {
  if (file.kind === "function") {
    return <FileCode2 size={14} />;
  }
  if (file.kind === "manifest" || file.path.endsWith(".json")) {
    return <FileJson size={14} />;
  }
  return <Braces size={14} />;
}

function emptySummary(namespace: string): CompileSummary {
  return {
    namespace,
    pack_format: "101.1",
    minecraft_version: "26.1.2",
    function_count: 0,
    command_count: 0,
    resource_count: 0,
    file_count: 0
  };
}

function fileMatchesView(file: CompileFile, view: OutputView) {
  switch (view) {
    case "functions":
      return file.kind === "function";
    case "resources":
      return file.kind === "tag" || (file.kind === "json" && !file.path.startsWith(".cobble/"));
    case "metadata":
      return file.path === "pack.mcmeta" || file.kind === "source-map";
    case "manifest":
      return file.kind === "manifest" || file.path === ".cobble/build_manifest.json";
    case "diagnostics":
      return false;
  }
}

function defaultActivePath(files: CompileFile[], view: OutputView) {
  return (
    files.find((file) => fileMatchesView(file, view))?.path ??
    files.find((file) => file.kind === "function")?.path ??
    files.find((file) => file.path === "pack.mcmeta")?.path ??
    files[0]?.path ??
    ""
  );
}

function downloadText(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/plain" });
  downloadBlob(blob, filename);
}

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
}

function downloadNameForPath(path: string) {
  return path.replace(/[^a-zA-Z0-9._-]+/g, "_");
}

function languageForFile(file: CompileFile): HighlightLanguage {
  if (file.kind === "function" || file.path.endsWith(".mcfunction")) {
    return "mcfunction";
  }
  if (
    file.kind === "json" ||
    file.kind === "tag" ||
    file.kind === "manifest" ||
    file.kind === "source-map" ||
    file.path.endsWith(".json") ||
    file.path.endsWith(".mcmeta")
  ) {
    return "json";
  }
  return "text";
}
