"use client";

import {
  Braces,
  CheckCircle2,
  Clipboard,
  Code2,
  Download,
  ExternalLink,
  FileCode2,
  Hammer,
  Loader2,
  Package,
  Play,
  RefreshCcw,
  Terminal,
  WandSparkles
} from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type CompileFile = {
  path: string;
  kind: string;
  content: string;
};

type CompileSummary = {
  namespace: string;
  pack_format: string;
  minecraft_version: string;
  function_count: number;
  command_count: number;
  file_count: number;
};

type CompileResult = {
  ok: boolean;
  files: CompileFile[];
  diagnostics: string[];
  summary: CompileSummary;
};

type WasmModule = {
  compile_cobble: (
    source: string,
    namespace?: string,
    description?: string
  ) => unknown;
};

const examples = [
  {
    name: "Load Flow",
    source: `score = 12

def on_load():
    /tellraw @a {"text":"Cobble demo loaded","color":"green"}
    /scoreboard objectives add demo dummy
    reward_player()

def reward_player():
    if score >= 10:
        /give @p minecraft:diamond 1
        /title @p title {"text":"Reward unlocked","color":"aqua"}
    else:
        /tellraw @p {"text":"Keep exploring","color":"yellow"}`
  },
  {
    name: "Macros",
    source: `def announce(player, item):
    /tellraw {player} {"text":"Crafted {item}!","color":"gold"}
    /playsound minecraft:block.note_block.pling master {player}

def on_load():
    announce("@a", "demo pack")`
  },
  {
    name: "Loops",
    source: `def countdown():
    for value in range(5):
        /tellraw @a {"text":"Tick {value}","color":"gray"}

def on_tick():
    countdown()`
  }
];

const defaultNamespace = "demo";
const description = "Generated by Cobble Web Demo";

export function CobbleDemo() {
  const [source, setSource] = useState(examples[0].source);
  const [namespace, setNamespace] = useState(defaultNamespace);
  const [result, setResult] = useState<CompileResult | null>(null);
  const [activePath, setActivePath] = useState("");
  const [wasm, setWasm] = useState<WasmModule | null>(null);
  const [status, setStatus] = useState<"loading" | "ready" | "compiling" | "error">(
    "loading"
  );
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    let active = true;

    async function loadWasm() {
      try {
        const mod = (await import("@/src/wasm/pkg/cobble_web_wasm.js")) as WasmModule;
        if (active) {
          setWasm(mod);
          setStatus("ready");
        }
      } catch (error) {
        if (active) {
          setStatus("error");
          setResult({
            ok: false,
            files: [],
            diagnostics: [error instanceof Error ? error.message : String(error)],
            summary: emptySummary(namespace)
          });
        }
      }
    }

    loadWasm();
    return () => {
      active = false;
    };
  }, [namespace]);

  useEffect(() => {
    if (!wasm) {
      return;
    }
    compile();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [wasm]);

  const activeFile = useMemo(() => {
    if (!result) {
      return null;
    }
    return result.files.find((file) => file.path === activePath) ?? result.files[0] ?? null;
  }, [activePath, result]);

  const functionFiles = result?.files.filter((file) => file.kind === "function") ?? [];
  const transcript = functionFiles
    .map((file) => `# ${file.path}\n${file.content.trimEnd()}`)
    .join("\n\n");

  function compile() {
    if (!wasm) {
      return;
    }

    setStatus("compiling");
    setCopied(false);

    window.setTimeout(() => {
      const compiled = wasm.compile_cobble(source, namespace, description) as CompileResult;
      setResult(compiled);
      setStatus(compiled.ok ? "ready" : "error");
      setActivePath(defaultActivePath(compiled.files));
    }, 0);
  }

  function resetExample(index = 0) {
    setSource(examples[index].source);
    setCopied(false);
  }

  async function copyTranscript() {
    if (!transcript) {
      return;
    }
    await navigator.clipboard.writeText(transcript);
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1600);
  }

  function downloadTranscript() {
    if (!transcript) {
      return;
    }
    const blob = new Blob([transcript], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = "cobble-transcript.mcfunction.txt";
    link.click();
    URL.revokeObjectURL(url);
  }

  return (
    <main>
      <section className="demo-shell">
        <img
          className="hero-image"
          src={`${process.env.NEXT_PUBLIC_BASE_PATH ?? ""}/cobble-workshop.jpg`}
          alt=""
        />
        <div className="hero-scrim" />

        <nav className="topbar" aria-label="Primary">
          <a className="brand" href="https://github.com/deveworld/cobble">
            <span className="brand-mark">C</span>
            <span>Cobble</span>
          </a>
          <div className="nav-actions">
            <a className="icon-button" href="https://docs.rs/cobble-lang/latest/cobble/" title="docs.rs">
              <Package size={18} />
            </a>
            <a className="icon-button" href="https://github.com/deveworld/cobble" title="GitHub">
              <ExternalLink size={18} />
            </a>
          </div>
        </nav>

        <div className="hero-copy">
          <p className="eyebrow">Minecraft Java Edition 26.1.2 · Pack Format 101.1</p>
          <h1>Cobble</h1>
          <p>
            A Python-like language that compiles into Minecraft data pack functions.
          </p>
        </div>

        <section className="workbench" aria-label="Cobble compiler demo">
          <div className="panel editor-panel">
            <div className="panel-toolbar">
              <div className="toolbar-title">
                <Code2 size={18} />
                <span>demo.cbl</span>
              </div>
              <div className="toolbar-actions">
                <label className="namespace-field">
                  <span>namespace</span>
                  <input
                    value={namespace}
                    onChange={(event) => setNamespace(event.target.value)}
                    spellCheck={false}
                  />
                </label>
                <button
                  className="icon-button"
                  type="button"
                  onClick={() => resetExample()}
                  title="Reset source"
                >
                  <RefreshCcw size={17} />
                </button>
                <button
                  className="command-button"
                  type="button"
                  onClick={compile}
                  disabled={!wasm || status === "compiling"}
                >
                  {status === "compiling" ? <Loader2 className="spin" size={17} /> : <Play size={17} />}
                  <span>Compile</span>
                </button>
              </div>
            </div>

            <div className="example-tabs" role="tablist" aria-label="Examples">
              {examples.map((example, index) => (
                <button
                  key={example.name}
                  type="button"
                  onClick={() => resetExample(index)}
                  className={source === example.source ? "selected" : ""}
                >
                  {example.name}
                </button>
              ))}
            </div>

            <textarea
              aria-label="Cobble source"
              value={source}
              onChange={(event) => setSource(event.target.value)}
              spellCheck={false}
            />
          </div>

          <div className="panel output-panel">
            <div className="panel-toolbar">
              <div className="toolbar-title">
                <Terminal size={18} />
                <span>mcfunction transcript</span>
              </div>
              <div className="toolbar-actions">
                <button
                  className="icon-button"
                  type="button"
                  onClick={copyTranscript}
                  disabled={!transcript}
                  title="Copy transcript"
                >
                  {copied ? <CheckCircle2 size={17} /> : <Clipboard size={17} />}
                </button>
                <button
                  className="icon-button"
                  type="button"
                  onClick={downloadTranscript}
                  disabled={!transcript}
                  title="Download transcript"
                >
                  <Download size={17} />
                </button>
              </div>
            </div>

            <StatusStrip result={result} status={status} />

            {result?.ok ? (
              <>
                <div className="file-tabs" role="tablist" aria-label="Generated files">
                  {result.files.map((file) => (
                    <button
                      key={file.path}
                      type="button"
                      onClick={() => setActivePath(file.path)}
                      className={file.path === activeFile?.path ? "selected" : ""}
                      title={file.path}
                    >
                      <FileCode2 size={14} />
                      <span>{file.path}</span>
                    </button>
                  ))}
                </div>
                <pre className="output-code">{activeFile?.content}</pre>
              </>
            ) : (
              <pre className="diagnostics">
                {(result?.diagnostics.length
                  ? result.diagnostics
                  : ["Loading Cobble WASM compiler..."]
                ).join("\n")}
              </pre>
            )}
          </div>
        </section>
      </section>

      <section className="details-band">
        <div className="detail">
          <WandSparkles size={20} />
          <strong>Browser WASM</strong>
          <span>Rust parser and transpiler run client-side.</span>
        </div>
        <div className="detail">
          <Hammer size={20} />
          <strong>Real output</strong>
          <span>Generated files mirror Cobble data pack paths.</span>
        </div>
        <div className="detail">
          <Braces size={20} />
          <strong>Source maps</strong>
          <span>Demo output includes Cobble metadata files.</span>
        </div>
      </section>
    </main>
  );
}

function StatusStrip({
  result,
  status
}: {
  result: CompileResult | null;
  status: "loading" | "ready" | "compiling" | "error";
}) {
  if (!result || status === "loading") {
    return (
      <div className="status-strip pending">
        <Loader2 className="spin" size={16} />
        <span>Loading compiler</span>
      </div>
    );
  }

  if (!result.ok) {
    return (
      <div className="status-strip failed">
        <span>{result.diagnostics.length} diagnostic</span>
      </div>
    );
  }

  return (
    <div className="status-strip">
      <span>{result.summary.function_count} functions</span>
      <span>{result.summary.command_count} commands</span>
      <span>{result.summary.file_count} files</span>
      <span>pack {result.summary.pack_format}</span>
    </div>
  );
}

function emptySummary(namespace: string): CompileSummary {
  return {
    namespace,
    pack_format: "101.1",
    minecraft_version: "26.1.2",
    function_count: 0,
    command_count: 0,
    file_count: 0
  };
}

function defaultActivePath(files: CompileFile[]) {
  return (
    files.find((file) => file.kind === "function")?.path ??
    files.find((file) => file.path === "pack.mcmeta")?.path ??
    files[0]?.path ??
    ""
  );
}
