use crate::config::CobbleConfig;
use crate::parser::parse;
use crate::transpiler::Transpiler;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};
use walkdir::WalkDir;
use zip::write::SimpleFileOptions;
use zip::{CompressionMethod, ZipWriter};

pub struct BuildOptions {
    pub input: Option<PathBuf>,
    pub output: Option<PathBuf>,
    pub namespace: Option<String>,
    pub pack_format: Option<u32>,
    pub description: Option<String>,
    pub verbose: bool,
    pub zip: bool,
}

pub fn build(options: BuildOptions) -> Result<(), String> {
    // Try to find cobble.toml
    let (config, config_dir) = if let Some(config_path) = find_config(&options.input) {
        let config = CobbleConfig::load(&config_path)?;
        let config_dir = config_path.parent().unwrap().to_path_buf();
        (Some(config), config_dir)
    } else {
        (
            None,
            std::env::current_dir().unwrap_or_else(|_| PathBuf::from(".")),
        )
    };

    // Determine source and output paths
    let source_path = if let Some(ref input) = options.input {
        input.clone()
    } else if let Some(ref cfg) = config {
        config_dir.join(&cfg.build.source)
    } else {
        return Err("No input specified and no cobble.toml found".to_string());
    };

    let output_dir = if let Some(ref output) = options.output {
        output.clone()
    } else if let Some(ref cfg) = config {
        config_dir.join(&cfg.build.output)
    } else {
        PathBuf::from("output")
    };

    // Get namespace from options, config, or use default
    let namespace = options
        .namespace
        .clone()
        .or_else(|| config.as_ref().map(|c| c.project.namespace.clone()))
        .unwrap_or_else(|| "cobble".to_string());

    let description = options
        .description
        .clone()
        .or_else(|| config.as_ref().map(|c| c.project.description.clone()))
        .unwrap_or_else(|| "Generated by Cobble".to_string());

    let pack_format = options
        .pack_format
        .or_else(|| config.as_ref().map(|c| c.project.pack_format as u32))
        .unwrap_or(88); // Minecraft 1.21.9+ (recommended)

    // Validate pack_format
    // Cobble requires Minecraft 1.21.7+ (pack format 81) for macro support
    const MIN_PACK_FORMAT: u32 = 81;
    if pack_format < MIN_PACK_FORMAT {
        return Err(format!(
            "pack_format must be at least {} (Minecraft 1.21.7+), got {}.\n\
            Cobble requires Minecraft 1.21.7 or newer for macro function support.\n\
            See https://minecraft.wiki/w/Pack_format for version compatibility.",
            MIN_PACK_FORMAT, pack_format
        ));
    } else if pack_format > 255 {
        return Err(format!(
            "pack_format must be between {} and 255, got {}",
            MIN_PACK_FORMAT, pack_format
        ));
    }

    // Check if source is a file or directory
    let files_to_compile = if source_path.is_file() {
        vec![source_path.clone()]
    } else if source_path.is_dir() {
        find_cobble_files(&source_path)?
    } else {
        return Err(format!("Source path does not exist: {:?}", source_path));
    };

    if files_to_compile.is_empty() {
        return Err("No Cobble files found to compile".to_string());
    }

    if options.verbose {
        println!("Building {} file(s)...", files_to_compile.len());
        println!("Namespace: {}", namespace);
        println!("Pack format: {}", pack_format);
        println!("Description: {}", description);
    } else {
        println!("Building {} file(s)...", files_to_compile.len());
    }

    // Create transpiler
    let mut transpiler = Transpiler::new(namespace.clone(), output_dir.clone());
    transpiler.set_description(description);
    transpiler.set_pack_format(pack_format as u8);

    // Compile all files
    for file_path in &files_to_compile {
        if options.verbose {
            println!(
                "  • Compiling: {:?}",
                file_path.file_name().unwrap_or_default()
            );
        } else {
            print!(
                "  • Compiling: {:?}",
                file_path.file_name().unwrap_or_default()
            );
        }

        let src = fs::read_to_string(file_path)
            .map_err(|e| format!("Failed to read {:?}: {}", file_path, e))?;

        let program = parse(&src).map_err(|errors| {
            format!(
                "Parse failed for {:?}:\n  {}",
                file_path,
                errors.join("\n  ")
            )
        })?;

        // Set current file for import resolution
        transpiler.set_current_file(file_path);

        transpiler
            .transpile(&program)
            .map_err(|e| format!("Transpilation failed for {:?}: {}", file_path, e))?;
    }

    // Write data pack
    transpiler
        .write_data_pack()
        .map_err(|e| format!("Failed to write data pack: {}", e))?;

    println!("✓ Data pack generated at {:?}", output_dir);

    // Create zip if requested
    if options.zip {
        create_zip(&output_dir, &namespace)?;
        println!("✓ Created {}.zip", namespace);
    }

    Ok(())
}

fn find_config(input: &Option<PathBuf>) -> Option<PathBuf> {
    if let Some(path) = input {
        if path.is_file() {
            // If input is a file, look for config in parent directories
            if let Some(parent) = path.parent() {
                return CobbleConfig::find_in_path(parent);
            }
        } else {
            // If input is a directory, look for config in it
            return CobbleConfig::find_in_path(path);
        }
    }
    // Look in current directory
    CobbleConfig::find_in_path(".")
}

fn find_cobble_files(dir: &Path) -> Result<Vec<PathBuf>, String> {
    let mut files = Vec::new();

    for entry in WalkDir::new(dir)
        .follow_links(true)
        .into_iter()
        .filter_map(|e| e.ok())
    {
        let path = entry.path();
        if path.is_file() {
            if let Some(ext) = path.extension() {
                if ext == "cbl" || ext == "cobble" {
                    files.push(path.to_path_buf());
                }
            }
        }
    }

    files.sort();
    Ok(files)
}

fn create_zip(output_dir: &Path, namespace: &str) -> Result<(), String> {
    let zip_path = output_dir.with_file_name(format!("{}.zip", namespace));
    let file =
        fs::File::create(&zip_path).map_err(|e| format!("Failed to create zip file: {}", e))?;

    let mut zip = ZipWriter::new(file);
    let options = SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);

    // Add all files from output directory to zip
    for entry in WalkDir::new(output_dir).into_iter().filter_map(|e| e.ok()) {
        let path = entry.path();
        if path.is_file() {
            let relative_path = path
                .strip_prefix(output_dir)
                .map_err(|e| format!("Failed to get relative path: {}", e))?;

            let file_data =
                fs::read(path).map_err(|e| format!("Failed to read file for zip: {}", e))?;

            // Convert path to use forward slashes for ZIP (required by Minecraft)
            let zip_path = relative_path.to_string_lossy().replace('\\', "/");

            zip.start_file(zip_path, options)
                .map_err(|e| format!("Failed to add file to zip: {}", e))?;

            zip.write_all(&file_data)
                .map_err(|e| format!("Failed to write file to zip: {}", e))?;
        }
    }

    zip.finish()
        .map_err(|e| format!("Failed to finalize zip: {}", e))?;

    Ok(())
}
