from stdlib import datapack, entity, event, item_component, position, schedule, selector, storage, text

datapack.item_modifier("items/reward_components", {
    "function": "minecraft:set_components",
    "components": item_component.components(
        item_component.custom_name(text.colored("Cobble Reward", "gold")),
        item_component.lore([
            text.plain("Generated by Cobble"),
            text.colored("Visible stdlib v3 JSON", "gray")
        ]),
        item_component.unbreakable()
    )
})

def load():
    storage.set(storage.path("players", "current"), "alex")
    storage.set(storage.child("players.current", "score"), 10)
    storage.get(storage.index("players.events", 0))
    text.tellraw(selector.all_players(), text.colored("Stdlib v3 helpers ready", "gold"))
    entity.teleport(selector.current(), position.relative(0, 1, 0))
    schedule.once("load", "20t", "replace")
    schedule.clear("load")

stdlib.addEventListener(event.LOAD, load)
