import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";

test("try page loads WASM compiler output and downloads a data pack ZIP", async ({
  page
}) => {
  await page.goto("/cobble/try/");

  await expect(page.getByRole("heading", { name: "Cobble" })).toBeVisible();
  await expect(page.getByLabel("Cobble source")).toContainText("def on_load");
  await expect(page.getByText("2 functions")).toBeVisible();
  await expect(page.getByText("5 commands")).toBeVisible();
  await expect(page.getByText("pack 101.1")).toBeVisible();

  await expect(
    page.getByRole("button", { name: "data/demo/function/on_load.mcfunction" })
  ).toBeVisible();
  await expect(page.locator(".output-code")).toContainText("tellraw @a");

  await page.getByRole("button", { name: /manifest/i }).click();
  await expect(
    page.getByRole("button", { name: ".cobble/build_manifest.json" })
  ).toBeVisible();
  await expect(page.locator(".output-code")).toContainText('"minecraft_version": "26.1.2"');

  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "ZIP" }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe("demo.zip");

  const downloadPath = await download.path();
  expect(downloadPath).toBeTruthy();
  const entries = readStoredZipEntries(await readFile(downloadPath!));
  expect(entries.map((entry) => entry.name)).toEqual([
    "data/demo/function/on_load.mcfunction",
    "data/demo/function/reward_player.mcfunction",
    "pack.mcmeta"
  ]);
  expect(entries.some((entry) => entry.name.startsWith(".cobble/"))).toBe(false);
  expect(entries.find((entry) => entry.name === "pack.mcmeta")?.content).toContain(
    "Generated by Cobble Web Demo"
  );
});

test("try page renders structured diagnostics for invalid source", async ({ page }) => {
  await page.goto("/cobble/try/");

  await expect(page.getByText("2 functions")).toBeVisible();
  await page
    .getByLabel("Cobble source")
    .fill("def reward(player, amount=1):\n    /say reward\n");
  await page.getByRole("button", { name: /compile/i }).click();

  await expect(page.getByText("1 diagnostic")).toBeVisible();
  await expect(page.locator(".diagnostic-heading code")).toHaveText(
    "unsupported-function-parameter"
  );
  await expect(page.locator(".diagnostic-card > p").first()).toHaveText(
    "Default parameter values are not supported"
  );
  await expect(page.locator(".diagnostic-location")).toHaveText("demo.cbl:1:26");
  await expect(page.locator(".diagnostic-snippet")).toContainText(
    "1 | def reward(player, amount=1):"
  );
  await expect(page.locator(".diagnostic-snippet")).toContainText("^");
});

test("try page diagnostic sample reports placeholder errors", async ({ page }) => {
  await page.goto("/cobble/try/");

  await expect(page.getByText("2 functions")).toBeVisible();
  await page.getByLabel("sample").selectOption({ label: "Diagnostic Example" });
  await page.getByRole("button", { name: /compile/i }).click();

  await expect(page.getByText("1 diagnostic")).toBeVisible();
  await expect(page.locator(".diagnostic-heading code")).toHaveText("undefined-placeholder");
  await expect(page.locator(".diagnostic-card > p").first()).toHaveText(
    "Undefined command placeholder `message`"
  );
});

test("try page renders resource sample outputs and ZIP entries", async ({ page }) => {
  await page.goto("/cobble/try/");

  await expect(page.getByText("2 functions")).toBeVisible();
  await page.getByLabel("sample").selectOption({ label: "Resources" });
  await page.getByRole("button", { name: /compile/i }).click();

  await expect(page.getByText("3 resources")).toBeVisible();
  await page.getByRole("button", { name: /resources/i }).click();
  await expect(
    page.getByRole("button", { name: "data/minecraft/tags/function/load.json" })
  ).toBeVisible();
  await expect(
    page.getByRole("button", { name: "data/resource_demo/predicate/checks/always.json" })
  ).toBeVisible();
  await expect(
    page.getByRole("button", { name: "data/resource_demo/dialog/notice.json" })
  ).toBeVisible();
  await expect(page.locator(".output-code")).toContainText("resource_demo:on_load");

  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "ZIP" }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toBe("resource_demo.zip");

  const downloadPath = await download.path();
  expect(downloadPath).toBeTruthy();
  const entries = readStoredZipEntries(await readFile(downloadPath!));
  expect(entries.map((entry) => entry.name)).toContain(
    "data/resource_demo/predicate/checks/always.json"
  );
  expect(entries.map((entry) => entry.name)).toContain("data/resource_demo/dialog/notice.json");
  expect(entries.map((entry) => entry.name)).toContain("data/minecraft/tags/function/load.json");
});

test("try page rejects invalid namespaces instead of sanitizing them", async ({ page }) => {
  await page.goto("/cobble/try/");

  await expect(page.getByText("2 functions")).toBeVisible();
  await page.getByLabel("namespace").fill("Bad Namespace!");
  await page.getByRole("button", { name: /compile/i }).click();

  await expect(page.getByText("1 diagnostic")).toBeVisible();
  await expect(page.locator(".diagnostic-heading code")).toHaveText("invalid-namespace");
  await expect(page.locator(".diagnostic-card > p").first()).toContainText(
    "Invalid namespace 'Bad Namespace!'"
  );
});

test("try page reports browser-only import diagnostics", async ({ page }) => {
  await page.goto("/cobble/try/");

  await expect(page.getByText("2 functions")).toBeVisible();
  await page.getByLabel("Cobble source").fill("import helper\n\ndef main():\n    pass\n");
  await page.getByRole("button", { name: /compile/i }).click();

  await expect(page.getByText("1 diagnostic")).toBeVisible();
  await expect(page.locator(".diagnostic-heading code")).toHaveText("missing-import");
  await expect(page.locator(".diagnostic-card > p").first()).toHaveText(
    "Cannot import 'helper': no import file is available"
  );
  await expect(page.locator(".diagnostic-help")).toContainText(
    "The browser compiler accepts one in-memory Cobble file"
  );
});

function readStoredZipEntries(buffer: Buffer) {
  const bytes = new Uint8Array(buffer);
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const decoder = new TextDecoder();
  const entries: Array<{ name: string; content: string }> = [];
  let offset = 0;

  while (offset < bytes.length && view.getUint32(offset, true) === 0x04034b50) {
    const compressedSize = view.getUint32(offset + 18, true);
    const nameLength = view.getUint16(offset + 26, true);
    const extraLength = view.getUint16(offset + 28, true);
    const nameStart = offset + 30;
    const dataStart = nameStart + nameLength + extraLength;
    const dataEnd = dataStart + compressedSize;

    entries.push({
      name: decoder.decode(bytes.slice(nameStart, nameStart + nameLength)),
      content: decoder.decode(bytes.slice(dataStart, dataEnd))
    });

    offset = dataEnd;
  }

  expect(view.getUint32(offset, true)).toBe(0x02014b50);
  return entries;
}
