use serde::Serialize;
use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};
use wasm_bindgen::prelude::*;

#[path = "../../../src/ast.rs"]
pub mod ast;
#[path = "../../../src/pack_format.rs"]
pub mod pack_format;
#[path = "../../../src/parser/mod.rs"]
pub mod parser;
#[path = "../../../src/stdlib.rs"]
pub mod stdlib;
#[path = "../../../src/transpiler/mod.rs"]
pub mod transpiler;

use pack_format::{SUPPORTED_MINECRAFT_VERSION, SUPPORTED_PACK_FORMAT};
use transpiler::{GeneratedCommand, GeneratedCommandKind, SourceMap, SourceMapEntry, Transpiler};

#[derive(Serialize)]
struct CompileFile {
    path: String,
    kind: String,
    content: String,
}

#[derive(Serialize)]
struct CompileSummary {
    namespace: String,
    pack_format: String,
    minecraft_version: String,
    function_count: usize,
    command_count: usize,
    file_count: usize,
}

#[derive(Serialize)]
struct CompileResponse {
    ok: bool,
    files: Vec<CompileFile>,
    diagnostics: Vec<String>,
    summary: CompileSummary,
}

#[wasm_bindgen(start)]
pub fn start() {
    console_error_panic_hook::set_once();
}

#[wasm_bindgen]
pub fn compile_cobble(source: &str, namespace: Option<String>, description: Option<String>) -> JsValue {
    let namespace = sanitize_namespace(namespace.as_deref().unwrap_or("demo"));
    let description = description.unwrap_or_else(|| "Generated by Cobble Web Demo".to_string());
    let response = match compile(source, &namespace, &description) {
        Ok(response) => response,
        Err(diagnostics) => CompileResponse {
            ok: false,
            files: Vec::new(),
            summary: CompileSummary {
                namespace,
                pack_format: SUPPORTED_PACK_FORMAT.to_string(),
                minecraft_version: SUPPORTED_MINECRAFT_VERSION.to_string(),
                function_count: 0,
                command_count: 0,
                file_count: 0,
            },
            diagnostics,
        },
    };

    serde_wasm_bindgen::to_value(&response).unwrap_or(JsValue::NULL)
}

fn compile(source: &str, namespace: &str, description: &str) -> Result<CompileResponse, Vec<String>> {
    let program = parser::parse(source).map_err(|errors| {
        errors
            .into_iter()
            .map(|error| format!("Parse error: {error}"))
            .collect::<Vec<_>>()
    })?;

    let mut transpiler = Transpiler::new(namespace.to_string(), PathBuf::from("cobble-web-demo"));
    transpiler.set_description(description.to_string());
    transpiler.set_pack_format(SUPPORTED_PACK_FORMAT);
    transpiler.set_current_file_with_source(Path::new("demo.cbl"), source);
    transpiler
        .transpile(&program)
        .map_err(|error| vec![format!("Transpile error: {error}")])?;

    let mut files = materialize_files(&transpiler, namespace, description)?;
    files.sort_by(|a, b| a.path.cmp(&b.path));
    let function_count = transpiler.data_pack.functions.len();
    let command_count = transpiler
        .data_pack
        .functions
        .values()
        .map(Vec::len)
        .sum::<usize>();
    let file_count = files.len();

    Ok(CompileResponse {
        ok: true,
        files,
        diagnostics: Vec::new(),
        summary: CompileSummary {
            namespace: namespace.to_string(),
            pack_format: SUPPORTED_PACK_FORMAT.to_string(),
            minecraft_version: SUPPORTED_MINECRAFT_VERSION.to_string(),
            function_count,
            command_count,
            file_count,
        },
    })
}

fn materialize_files(
    transpiler: &Transpiler,
    namespace: &str,
    description: &str,
) -> Result<Vec<CompileFile>, Vec<String>> {
    let pack = &transpiler.data_pack;
    let mut files = Vec::new();

    files.push(CompileFile {
        path: "pack.mcmeta".to_string(),
        kind: "metadata".to_string(),
        content: serde_json::to_string_pretty(&serde_json::json!({
            "pack": {
                "description": description,
                "min_format": [101, 1],
                "max_format": [101, 1]
            }
        }))
        .map_err(to_diag)?,
    });

    let mut source_map_entries = Vec::new();
    let mut function_names = pack.functions.keys().collect::<Vec<_>>();
    function_names.sort();
    for name in function_names {
        let commands = &pack.functions[name];
        let generated_path = format!("data/{namespace}/function/{name}.mcfunction");
        for (index, command) in commands.iter().enumerate() {
            let metadata = pack
                .command_metadata
                .get(name)
                .and_then(|commands| commands.get(&index))
                .cloned()
                .unwrap_or_else(|| {
                    GeneratedCommand::new(
                        command.clone(),
                        None,
                        GeneratedCommandKind::ControlFlow,
                    )
                });
            source_map_entries.push(SourceMapEntry {
                generated_path: generated_path.clone(),
                generated_line: index + 1,
                command: metadata.text,
                source: metadata.source,
                kind: metadata.kind,
            });
        }
        files.push(CompileFile {
            path: generated_path,
            kind: "function".to_string(),
            content: join_commands(commands),
        });
    }

    let stdlib_tags = pack.stdlib.generate_tags(namespace);
    for (tag_name, functions) in stdlib_tags {
        push_function_tag(&mut files, namespace, &tag_name, &functions)?;
    }
    let mut tag_names = pack.tags.keys().collect::<Vec<_>>();
    tag_names.sort();
    for tag_name in tag_names {
        push_function_tag(&mut files, namespace, tag_name, &pack.tags[tag_name])?;
    }

    push_named_json_resources(&mut files, namespace, "advancement", &pack.advancements);
    push_named_json_resources(&mut files, namespace, "loot_table", &pack.loot_tables);
    push_named_json_resources(&mut files, namespace, "recipe", &pack.recipes);
    push_named_json_resources(&mut files, namespace, "predicate", &pack.predicates);
    push_named_json_resources(&mut files, namespace, "item_modifier", &pack.item_modifiers);

    let mut json_resource_paths = pack.json_resources.keys().collect::<Vec<_>>();
    json_resource_paths.sort();
    for key in json_resource_paths {
        if let Some((resource_namespace, relative_path)) = key.split_once('/') {
            files.push(CompileFile {
                path: format!("data/{resource_namespace}/{relative_path}.json"),
                kind: "json".to_string(),
                content: pack.json_resources[key].clone(),
            });
        }
    }

    if !source_map_entries.is_empty() {
        files.push(CompileFile {
            path: ".cobble/source_map.json".to_string(),
            kind: "source-map".to_string(),
            content: serde_json::to_string_pretty(&SourceMap {
                version: 1,
                entries: source_map_entries,
            })
            .map_err(to_diag)?,
        });
    }

    let generated_namespaces = generated_namespaces(pack, namespace);
    files.push(CompileFile {
        path: ".cobble/generated_namespaces.json".to_string(),
        kind: "source-map".to_string(),
        content: serde_json::to_string_pretty(&generated_namespaces).map_err(to_diag)?,
    });

    Ok(files)
}

fn push_function_tag(
    files: &mut Vec<CompileFile>,
    default_namespace: &str,
    tag_name: &str,
    functions: &[String],
) -> Result<(), Vec<String>> {
    let (namespace, relative_tag_name) = tag_name
        .split_once(':')
        .unwrap_or((default_namespace, tag_name));
    files.push(CompileFile {
        path: format!("data/{namespace}/tags/function/{relative_tag_name}.json"),
        kind: "tag".to_string(),
        content: serde_json::to_string_pretty(&serde_json::json!({ "values": functions }))
            .map_err(to_diag)?,
    });
    Ok(())
}

fn push_named_json_resources(
    files: &mut Vec<CompileFile>,
    namespace: &str,
    resource_dir: &str,
    resources: &HashMap<String, String>,
) {
    let mut names = resources.keys().collect::<Vec<_>>();
    names.sort();
    for name in names {
        files.push(CompileFile {
            path: format!("data/{namespace}/{resource_dir}/{name}.json"),
            kind: "json".to_string(),
            content: resources[name].clone(),
        });
    }
}

fn generated_namespaces(pack: &transpiler::DataPack, namespace: &str) -> Vec<String> {
    let mut namespaces = HashSet::new();
    namespaces.insert(namespace.to_string());
    namespaces.insert("minecraft".to_string());
    for key in pack.json_resources.keys() {
        if let Some((resource_namespace, _)) = key.split_once('/') {
            namespaces.insert(resource_namespace.to_string());
        }
    }
    for tag_name in pack.tags.keys() {
        if let Some((resource_namespace, _)) = tag_name.split_once(':') {
            namespaces.insert(resource_namespace.to_string());
        }
    }
    let mut namespaces = namespaces.into_iter().collect::<Vec<_>>();
    namespaces.sort();
    namespaces
}

fn join_commands(commands: &[String]) -> String {
    let mut output = commands.join("\n");
    if !output.is_empty() {
        output.push('\n');
    }
    output
}

fn sanitize_namespace(namespace: &str) -> String {
    let mut sanitized = namespace
        .chars()
        .map(|ch| {
            let ch = ch.to_ascii_lowercase();
            if ch.is_ascii_lowercase() || ch.is_ascii_digit() || ch == '_' || ch == '-' || ch == '.'
            {
                ch
            } else {
                '_'
            }
        })
        .collect::<String>();

    if sanitized.is_empty() {
        sanitized = "demo".to_string();
    }
    sanitized.truncate(64);
    sanitized
}

fn to_diag(error: serde_json::Error) -> Vec<String> {
    vec![format!("Serialization error: {error}")]
}
