use serde::Serialize;
use std::collections::{HashMap, HashSet};
use std::path::{Path, PathBuf};
use wasm_bindgen::prelude::*;

#[path = "../../../src/ast.rs"]
pub mod ast;
#[path = "../../../src/diagnostics.rs"]
pub mod diagnostics;
#[path = "../../../src/pack_format.rs"]
pub mod pack_format;
#[path = "../../../src/parser/mod.rs"]
pub mod parser;
#[path = "../../../src/stdlib.rs"]
pub mod stdlib;
#[path = "../../../src/transpiler/mod.rs"]
pub mod transpiler;

use pack_format::{SUPPORTED_MINECRAFT_VERSION, SUPPORTED_PACK_FORMAT};
use transpiler::{
    BuildManifestInput, GeneratedCommand, GeneratedCommandKind, SourceMap, SourceMapEntry,
    Transpiler,
};

const DEFAULT_NAMESPACE: &str = "cobble";

#[derive(Serialize)]
struct CompileFile {
    path: String,
    kind: String,
    content: String,
}

#[derive(Serialize)]
struct CompileSummary {
    namespace: String,
    pack_format: String,
    minecraft_version: String,
    function_count: usize,
    command_count: usize,
    resource_count: usize,
    file_count: usize,
}

#[derive(Clone, Debug, Serialize)]
struct CompileDiagnostic {
    file: String,
    line: usize,
    column: usize,
    severity: String,
    kind: String,
    message: String,
    help: Option<String>,
    formatted: String,
}

#[derive(Serialize)]
struct CompileResponse {
    ok: bool,
    files: Vec<CompileFile>,
    diagnostics: Vec<String>,
    diagnostic_details: Vec<CompileDiagnostic>,
    summary: CompileSummary,
}

#[wasm_bindgen(start)]
pub fn start() {
    console_error_panic_hook::set_once();
}

#[wasm_bindgen]
pub fn compile_cobble(
    source: &str,
    namespace: Option<String>,
    description: Option<String>,
) -> JsValue {
    let namespace = namespace.unwrap_or_else(|| DEFAULT_NAMESPACE.to_string());
    let description = description.unwrap_or_else(|| "Generated by Cobble Web Demo".to_string());
    let response = match validate_namespace(&namespace)
        .map_err(|diagnostic| vec![diagnostic])
        .and_then(|_| compile(source, &namespace, &description))
    {
        Ok(response) => response,
        Err(diagnostic_details) => {
            let diagnostics = formatted_diagnostics(&diagnostic_details);
            CompileResponse {
                ok: false,
                files: Vec::new(),
                summary: CompileSummary {
                    namespace,
                    pack_format: SUPPORTED_PACK_FORMAT.to_string(),
                    minecraft_version: SUPPORTED_MINECRAFT_VERSION.to_string(),
                    function_count: 0,
                    command_count: 0,
                    resource_count: 0,
                    file_count: 0,
                },
                diagnostics,
                diagnostic_details,
            }
        }
    };

    serde_wasm_bindgen::to_value(&response).unwrap_or(JsValue::NULL)
}

fn compile(
    source: &str,
    namespace: &str,
    description: &str,
) -> Result<CompileResponse, Vec<CompileDiagnostic>> {
    let program = diagnostics::parse_source(source)
        .map_err(|diagnostics| source_diagnostics("demo.cbl", source, diagnostics))?;
    let import_diagnostics = diagnostics::analyze_in_memory_imports(source, &program.imports);
    if !import_diagnostics.is_empty() {
        return Err(source_diagnostics(
            "demo.cbl",
            source,
            import_diagnostics,
        ));
    }

    let mut transpiler = Transpiler::new(namespace.to_string(), PathBuf::from("cobble-web-demo"));
    transpiler.set_description(description.to_string());
    transpiler.set_pack_format(SUPPORTED_PACK_FORMAT);
    transpiler.set_build_input(BuildManifestInput {
        source: "demo.cbl".to_string(),
        entry_points: Vec::new(),
        compiled_files: vec!["demo.cbl".to_string()],
    });
    transpiler.set_current_file_with_source(Path::new("demo.cbl"), source);
    transpiler.transpile(&program).map_err(|error| {
        vec![generic_diagnostic(
            "transpile",
            format!("Transpile error: {error}"),
        )]
    })?;

    let mut files = materialize_files(&transpiler, namespace, description)?;
    files.sort_by(|a, b| a.path.cmp(&b.path));
    let function_count = transpiler.data_pack.functions.len();
    let command_count = transpiler
        .data_pack
        .functions
        .values()
        .map(Vec::len)
        .sum::<usize>();
    let resource_count = transpiler
        .data_pack
        .build_manifest_snapshot()
        .resources
        .len();
    let file_count = files.len();

    Ok(CompileResponse {
        ok: true,
        files,
        diagnostics: Vec::new(),
        diagnostic_details: Vec::new(),
        summary: CompileSummary {
            namespace: namespace.to_string(),
            pack_format: SUPPORTED_PACK_FORMAT.to_string(),
            minecraft_version: SUPPORTED_MINECRAFT_VERSION.to_string(),
            function_count,
            command_count,
            resource_count,
            file_count,
        },
    })
}

fn materialize_files(
    transpiler: &Transpiler,
    namespace: &str,
    description: &str,
) -> Result<Vec<CompileFile>, Vec<CompileDiagnostic>> {
    let pack = &transpiler.data_pack;
    let mut files = Vec::new();

    files.push(CompileFile {
        path: "pack.mcmeta".to_string(),
        kind: "metadata".to_string(),
        content: serde_json::to_string_pretty(&serde_json::json!({
            "pack": {
                "description": description,
                "min_format": [101, 1],
                "max_format": [101, 1]
            }
        }))
        .map_err(to_diag)?,
    });

    let mut source_map_entries = Vec::new();
    let mut function_names = pack.functions.keys().collect::<Vec<_>>();
    function_names.sort();
    for name in function_names {
        let commands = &pack.functions[name];
        let generated_path = format!("data/{namespace}/function/{name}.mcfunction");
        for (index, command) in commands.iter().enumerate() {
            let metadata = pack
                .command_metadata
                .get(name)
                .and_then(|commands| commands.get(&index))
                .cloned()
                .unwrap_or_else(|| {
                    GeneratedCommand::new(command.clone(), None, GeneratedCommandKind::ControlFlow)
                });
            source_map_entries.push(SourceMapEntry {
                generated_path: generated_path.clone(),
                generated_line: index + 1,
                command: metadata.text,
                source: metadata.source,
                kind: metadata.kind,
            });
        }
        files.push(CompileFile {
            path: generated_path,
            kind: "function".to_string(),
            content: join_commands(commands),
        });
    }

    let stdlib_tags = pack.stdlib.generate_tags(namespace);
    for (tag_name, functions) in stdlib_tags {
        push_function_tag(&mut files, namespace, &tag_name, &functions)?;
    }
    let mut tag_names = pack.tags.keys().collect::<Vec<_>>();
    tag_names.sort();
    for tag_name in tag_names {
        push_function_tag(&mut files, namespace, tag_name, &pack.tags[tag_name])?;
    }

    push_named_json_resources(&mut files, namespace, "advancement", &pack.advancements);
    push_named_json_resources(&mut files, namespace, "loot_table", &pack.loot_tables);
    push_named_json_resources(&mut files, namespace, "recipe", &pack.recipes);
    push_named_json_resources(&mut files, namespace, "predicate", &pack.predicates);
    push_named_json_resources(&mut files, namespace, "item_modifier", &pack.item_modifiers);

    let mut json_resource_paths = pack.json_resources.keys().collect::<Vec<_>>();
    json_resource_paths.sort();
    for key in json_resource_paths {
        if let Some((resource_namespace, relative_path)) = key.split_once('/') {
            let kind = if relative_path.starts_with("tags/") {
                "tag"
            } else {
                "json"
            };
            push_or_merge_file(
                &mut files,
                CompileFile {
                    path: format!("data/{resource_namespace}/{relative_path}.json"),
                    kind: kind.to_string(),
                    content: pack.json_resources[key].clone(),
                },
            )?;
        }
    }

    if !source_map_entries.is_empty() {
        files.push(CompileFile {
            path: ".cobble/source_map.json".to_string(),
            kind: "source-map".to_string(),
            content: serde_json::to_string_pretty(&SourceMap {
                version: 1,
                entries: source_map_entries,
            })
            .map_err(to_diag)?,
        });
    }

    let generated_namespaces = generated_namespaces(pack, namespace);
    files.push(CompileFile {
        path: ".cobble/generated_namespaces.json".to_string(),
        kind: "source-map".to_string(),
        content: serde_json::to_string_pretty(&generated_namespaces).map_err(to_diag)?,
    });

    files.push(CompileFile {
        path: ".cobble/build_manifest.json".to_string(),
        kind: "manifest".to_string(),
        content: serde_json::to_string_pretty(&pack.build_manifest_snapshot()).map_err(to_diag)?,
    });

    Ok(files)
}

fn push_function_tag(
    files: &mut Vec<CompileFile>,
    default_namespace: &str,
    tag_name: &str,
    functions: &[String],
) -> Result<(), Vec<CompileDiagnostic>> {
    let (namespace, relative_tag_name) = tag_name
        .split_once(':')
        .unwrap_or((default_namespace, tag_name));
    push_or_merge_file(
        files,
        CompileFile {
            path: format!("data/{namespace}/tags/function/{relative_tag_name}.json"),
            kind: "tag".to_string(),
            content: serde_json::to_string_pretty(&serde_json::json!({ "values": functions }))
                .map_err(to_diag)?,
        },
    )
}

fn push_or_merge_file(
    files: &mut Vec<CompileFile>,
    file: CompileFile,
) -> Result<(), Vec<CompileDiagnostic>> {
    if let Some(existing) = files.iter_mut().find(|existing| existing.path == file.path) {
        if is_tag_path(&file.path) {
            existing.content = merge_tag_json(&existing.content, &file.content)?;
            if file.kind == "tag" {
                existing.kind = file.kind;
            }
            return Ok(());
        }
    }

    files.push(file);
    Ok(())
}

fn is_tag_path(path: &str) -> bool {
    path.starts_with("data/") && path.contains("/tags/") && path.ends_with(".json")
}

fn merge_tag_json(
    existing_json: &str,
    new_json: &str,
) -> Result<String, Vec<CompileDiagnostic>> {
    let Ok(mut merged_value) = serde_json::from_str::<serde_json::Value>(existing_json) else {
        return Ok(new_json.to_string());
    };
    let Ok(new_value) = serde_json::from_str::<serde_json::Value>(new_json) else {
        return Ok(new_json.to_string());
    };

    let Some(merged_values) = merged_value
        .get_mut("values")
        .and_then(|value| value.as_array_mut())
    else {
        return Ok(new_json.to_string());
    };
    let Some(new_values) = new_value.get("values").and_then(|value| value.as_array()) else {
        return Ok(new_json.to_string());
    };

    for new_value in new_values {
        if !merged_values.contains(new_value) {
            merged_values.push(new_value.clone());
        }
    }

    serde_json::to_string_pretty(&merged_value).map_err(to_diag)
}

fn push_named_json_resources(
    files: &mut Vec<CompileFile>,
    namespace: &str,
    resource_dir: &str,
    resources: &HashMap<String, String>,
) {
    let mut names = resources.keys().collect::<Vec<_>>();
    names.sort();
    for name in names {
        files.push(CompileFile {
            path: format!("data/{namespace}/{resource_dir}/{name}.json"),
            kind: "json".to_string(),
            content: resources[name].clone(),
        });
    }
}

fn generated_namespaces(pack: &transpiler::DataPack, namespace: &str) -> Vec<String> {
    let mut namespaces = HashSet::new();
    namespaces.insert(namespace.to_string());
    namespaces.insert("minecraft".to_string());
    for key in pack.json_resources.keys() {
        if let Some((resource_namespace, _)) = key.split_once('/') {
            namespaces.insert(resource_namespace.to_string());
        }
    }
    for tag_name in pack.tags.keys() {
        if let Some((resource_namespace, _)) = tag_name.split_once(':') {
            namespaces.insert(resource_namespace.to_string());
        }
    }
    let mut namespaces = namespaces.into_iter().collect::<Vec<_>>();
    namespaces.sort();
    namespaces
}

fn join_commands(commands: &[String]) -> String {
    let mut output = commands.join("\n");
    if !output.is_empty() {
        output.push('\n');
    }
    output
}

fn validate_namespace(namespace: &str) -> Result<(), CompileDiagnostic> {
    if namespace.is_empty() {
        return Err(namespace_diagnostic(
            "Namespace cannot be empty".to_string(),
            "Use a lowercase namespace such as `my_datapack` or `cool-pack.v2`.",
        ));
    }
    if namespace.len() > 64 {
        return Err(namespace_diagnostic(
            format!("Namespace too long: {} chars (max 64)", namespace.len()),
            "Keep the namespace at 64 characters or fewer.",
        ));
    }
    if !namespace
        .chars()
        .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_' || c == '-' || c == '.')
    {
        return Err(namespace_diagnostic(
            format!("Invalid namespace '{namespace}'"),
            "Namespaces can only contain lowercase letters, digits, underscores, hyphens, and dots.",
        ));
    }

    Ok(())
}

fn namespace_diagnostic(message: String, help: &str) -> CompileDiagnostic {
    let diagnostic =
        diagnostics::SourceDiagnostic::error("invalid-namespace", 1, 1, message).with_help(help);
    source_diagnostics("namespace", "", vec![diagnostic])
        .into_iter()
        .next()
        .expect("namespace diagnostic is present")
}

fn source_diagnostics(
    filename: &str,
    source: &str,
    diagnostics: Vec<diagnostics::SourceDiagnostic>,
) -> Vec<CompileDiagnostic> {
    diagnostics
        .into_iter()
        .map(|diagnostic| {
            let formatted = if source.is_empty() {
                diagnostic.format_compact(filename)
            } else {
                diagnostic.format_with_source(filename, source)
            };
            CompileDiagnostic {
                file: filename.to_string(),
                line: diagnostic.line,
                column: diagnostic.column,
                severity: diagnostic.severity.as_str().to_string(),
                kind: diagnostic.kind,
                message: diagnostic.message,
                help: diagnostic.help,
                formatted,
            }
        })
        .collect()
}

fn generic_diagnostic(kind: &str, message: String) -> CompileDiagnostic {
    let source = diagnostics::SourceDiagnostic::error(kind, 1, 1, message);
    source_diagnostics("demo.cbl", "", vec![source])
        .into_iter()
        .next()
        .expect("generic diagnostic is present")
}

fn formatted_diagnostics(diagnostics: &[CompileDiagnostic]) -> Vec<String> {
    diagnostics
        .iter()
        .map(|diagnostic| diagnostic.formatted.clone())
        .collect()
}

fn to_diag(error: serde_json::Error) -> Vec<CompileDiagnostic> {
    vec![generic_diagnostic(
        "serialization",
        format!("Serialization error: {error}"),
    )]
}

#[cfg(test)]
mod tests {
    use super::*;

    fn file<'a>(response: &'a CompileResponse, path: &str) -> &'a CompileFile {
        response
            .files
            .iter()
            .find(|file| file.path == path)
            .unwrap_or_else(|| panic!("missing generated file {path}"))
    }

    #[test]
    fn compile_manifest_reports_root_cobble_version() {
        let response = compile("def load():\n    /say web\n", "web_test", "Web test").unwrap();

        let manifest: serde_json::Value =
            serde_json::from_str(&file(&response, ".cobble/build_manifest.json").content).unwrap();

        assert_eq!(manifest["cobble_version"], env!("COBBLE_LANG_VERSION"));
        assert_eq!(manifest["minecraft_version"], "26.1.2");
        assert_eq!(manifest["pack_format_text"], "101.1");
        assert_eq!(manifest["namespace"], "web_test");
    }

    #[test]
    fn compile_merges_duplicate_function_tag_paths() {
        let response = compile(
            r#"
import stdlib
from stdlib import event

datapack.function_tag("minecraft:load", ["web_test:extra_load"])

def load():
    /say load

def extra_load():
    /say extra

stdlib.addEventListener(event.LOAD, load)
"#,
            "web_test",
            "Web test",
        )
        .unwrap();

        let load_tag_files: Vec<_> = response
            .files
            .iter()
            .filter(|file| file.path == "data/minecraft/tags/function/load.json")
            .collect();
        assert_eq!(load_tag_files.len(), 1);

        let tag: serde_json::Value = serde_json::from_str(&load_tag_files[0].content).unwrap();
        assert_eq!(
            tag["values"],
            serde_json::json!(["web_test:load", "web_test:extra_load"])
        );
    }

    #[test]
    fn compile_returns_structured_parse_diagnostics() {
        let diagnostics = match compile("def broken():\n    ?\n", "web_test", "Web test") {
            Ok(_) => panic!("invalid source should fail"),
            Err(diagnostics) => diagnostics,
        };

        assert!(!diagnostics.is_empty());
        assert_eq!(diagnostics[0].file, "demo.cbl");
        assert_eq!(diagnostics[0].line, 1);
        assert_eq!(diagnostics[0].column, 1);
        assert_eq!(diagnostics[0].kind, "parse");
        assert!(diagnostics[0].message.contains("Parse error:"));
        assert!(diagnostics[0].formatted.contains("demo.cbl:1:1"));
        assert!(diagnostics[0].formatted.contains("1 | def broken():"));
        assert!(diagnostics[0].formatted.contains("| ^"));
    }

    #[test]
    fn compile_returns_language_surface_diagnostics() {
        let diagnostics = match compile(
            "def reward(player, amount=1):\n    /say reward\n",
            "web_test",
            "Web test",
        ) {
            Ok(_) => panic!("unsupported source should fail"),
            Err(diagnostics) => diagnostics,
        };

        assert_eq!(diagnostics.len(), 1);
        assert_eq!(diagnostics[0].file, "demo.cbl");
        assert_eq!(diagnostics[0].line, 1);
        assert_eq!(diagnostics[0].column, 26);
        assert_eq!(diagnostics[0].kind, "unsupported-function-parameter");
        assert!(diagnostics[0]
            .message
            .contains("Default parameter values are not supported"));
    }

    #[test]
    fn compile_returns_in_memory_import_diagnostics() {
        let diagnostics = match compile(
            "import helper\n\ndef main():\n    pass\n",
            "web_test",
            "Web test",
        ) {
            Ok(_) => panic!("missing import should fail"),
            Err(diagnostics) => diagnostics,
        };

        assert_eq!(diagnostics.len(), 1);
        assert_eq!(diagnostics[0].file, "demo.cbl");
        assert_eq!(diagnostics[0].line, 1);
        assert_eq!(diagnostics[0].column, 8);
        assert_eq!(diagnostics[0].kind, "missing-import");
        assert!(diagnostics[0]
            .message
            .contains("Cannot import 'helper'"));
    }

    #[test]
    fn compile_returns_semantic_preflight_diagnostics() {
        let diagnostics = match compile(
            "def main():\n    return\n",
            "web_test",
            "Web test",
        ) {
            Ok(_) => panic!("unsupported source should fail"),
            Err(diagnostics) => diagnostics,
        };

        assert_eq!(diagnostics.len(), 1);
        assert_eq!(diagnostics[0].file, "demo.cbl");
        assert_eq!(diagnostics[0].line, 2);
        assert_eq!(diagnostics[0].column, 5);
        assert_eq!(diagnostics[0].kind, "unsupported-return");
        assert!(diagnostics[0]
            .message
            .contains("Return statements are not supported"));
    }

    #[test]
    fn compile_returns_user_function_argument_count_diagnostics() {
        let diagnostics = match compile(
            "def main():\n    greet(\"@a\")\n\ndef greet(player, message):\n    /say hi\n",
            "web_test",
            "Web test",
        ) {
            Ok(_) => panic!("unsupported source should fail"),
            Err(diagnostics) => diagnostics,
        };

        assert_eq!(diagnostics.len(), 1);
        assert_eq!(diagnostics[0].file, "demo.cbl");
        assert_eq!(diagnostics[0].kind, "function-argument-count");
        assert!(diagnostics[0]
            .message
            .contains("Function `greet` expects 2 argument(s), but 1 provided"));
    }

    #[test]
    fn compile_returns_nested_function_argument_diagnostics() {
        let diagnostics = match compile(
            "def main():\n    greet(make_name())\n\ndef make_name():\n    pass\n\ndef greet(name):\n    /say hi\n",
            "web_test",
            "Web test",
        ) {
            Ok(_) => panic!("unsupported source should fail"),
            Err(diagnostics) => diagnostics,
        };

        assert_eq!(diagnostics.len(), 1);
        assert_eq!(diagnostics[0].file, "demo.cbl");
        assert_eq!(diagnostics[0].kind, "unsupported-function-call-argument");
        assert!(diagnostics[0]
            .message
            .contains("Function `greet` arguments cannot contain function call expressions"));
    }

    #[test]
    fn compile_returns_raw_command_placeholder_diagnostics() {
        let diagnostics = match compile(
            "def greet(player):\n    /tellraw {player} {\"text\":\"Hello {message}\"}\n",
            "web_test",
            "Web test",
        ) {
            Ok(_) => panic!("unsupported source should fail"),
            Err(diagnostics) => diagnostics,
        };

        assert_eq!(diagnostics.len(), 1);
        assert_eq!(diagnostics[0].file, "demo.cbl");
        assert_eq!(diagnostics[0].kind, "undefined-placeholder");
        assert!(diagnostics[0]
            .message
            .contains("Undefined command placeholder `message`"));
    }

    #[test]
    fn compile_returns_noop_expression_diagnostics() {
        let diagnostics = match compile("def main():\n    score + 1\n", "web_test", "Web test") {
            Ok(_) => panic!("no-op source should fail"),
            Err(diagnostics) => diagnostics,
        };

        assert_eq!(diagnostics.len(), 1);
        assert_eq!(diagnostics[0].file, "demo.cbl");
        assert_eq!(diagnostics[0].line, 2);
        assert_eq!(diagnostics[0].column, 5);
        assert_eq!(diagnostics[0].kind, "no-op-expression");
        assert!(diagnostics[0]
            .message
            .contains("Standalone expression does not generate Minecraft commands"));
    }

    #[test]
    fn compile_returns_datapack_resource_id_diagnostics() {
        let diagnostics = match compile(
            "datapack.item_tag(\"rewards\", [\"minecraft/diamond\"])\n",
            "web_test",
            "Web test",
        ) {
            Ok(_) => panic!("invalid resource ID should fail"),
            Err(diagnostics) => diagnostics,
        };

        assert_eq!(diagnostics.len(), 1);
        assert_eq!(diagnostics[0].file, "demo.cbl");
        assert_eq!(diagnostics[0].line, 1);
        assert_eq!(diagnostics[0].kind, "datapack-resource-id");
        assert!(diagnostics[0]
            .message
            .contains("Use 'minecraft:diamond' instead"));
    }

    #[test]
    fn validate_namespace_rejects_cli_invalid_namespaces() {
        let diagnostic =
            validate_namespace("Bad Namespace!").expect_err("invalid namespace should fail");

        assert_eq!(diagnostic.kind, "invalid-namespace");
        assert!(diagnostic.message.contains("Invalid namespace"));
        assert!(diagnostic
            .help
            .as_deref()
            .unwrap()
            .contains("lowercase letters"));
    }

    #[test]
    fn default_namespace_matches_cli_build_default() {
        assert_eq!(DEFAULT_NAMESPACE, "cobble");
        let response = compile("def load():\n    /say hi\n", DEFAULT_NAMESPACE, "Web test")
            .expect("default namespace should compile");

        assert_eq!(response.summary.namespace, "cobble");
        assert!(response
            .files
            .iter()
            .any(|file| file.path == "data/cobble/function/load.mcfunction"));
    }

    #[test]
    fn compile_cobble_response_includes_legacy_and_structured_diagnostics() {
        let diagnostic_details = match compile(
            "def reward(player, amount=1):\n    /say reward\n",
            "web_test",
            "Web test",
        ) {
            Ok(_) => panic!("unsupported source should fail"),
            Err(diagnostics) => diagnostics,
        };
        let diagnostics = formatted_diagnostics(&diagnostic_details);
        let response = serde_json::to_value(CompileResponse {
            ok: false,
            files: Vec::new(),
            diagnostics,
            diagnostic_details,
            summary: CompileSummary {
                namespace: "web_test".to_string(),
                pack_format: SUPPORTED_PACK_FORMAT.to_string(),
                minecraft_version: SUPPORTED_MINECRAFT_VERSION.to_string(),
                function_count: 0,
                command_count: 0,
                resource_count: 0,
                file_count: 0,
            },
        })
        .unwrap();

        assert_eq!(response["ok"], false);
        assert!(response["diagnostics"][0]
            .as_str()
            .unwrap()
            .contains("unsupported-function-parameter"));
        assert_eq!(
            response["diagnostic_details"][0]["kind"],
            "unsupported-function-parameter"
        );
        assert_eq!(
            response["diagnostics"].as_array().unwrap().len(),
            response["diagnostic_details"].as_array().unwrap().len()
        );
        assert_eq!(
            response["diagnostics"][0],
            response["diagnostic_details"][0]["formatted"]
        );
        assert_eq!(response["diagnostic_details"][0]["file"], "demo.cbl");
        assert_eq!(response["diagnostic_details"][0]["line"], 1);
        assert_eq!(response["diagnostic_details"][0]["column"], 26);
    }
}
