#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

run() {
  echo "+ $*"
  "$@"
}

assert_json_field() {
  local label="$1"
  local file="$2"
  local expression="$3"
  python3 - "$label" "$file" "$expression" <<'PY'
import json
import sys

label = sys.argv[1]
path = sys.argv[2]
expression = sys.argv[3]
with open(path, encoding="utf-8") as handle:
    data = json.load(handle)
if not eval(expression, {}, {"data": data}):
    raise SystemExit(
        f"{label} failed JSON assertion: {expression}\n"
        f"{json.dumps(data, indent=2)}"
    )
PY
}

package_args=(--locked)
if [[ "${COBBLE_QA_ALLOW_DIRTY:-}" == "1" ]]; then
  package_args+=(--allow-dirty)
fi

echo "== Core Rust gate =="
run cargo fmt --check
run git diff --check
run cargo check --locked
run cargo test --locked
run cargo clippy --locked --all-targets -- -D warnings
run cargo run --locked -- --version
version_output="$(cargo run --locked --quiet -- --version)"
if [[ "$version_output" != *"0.9.0"* ]]; then
  echo "Expected cobble --version to report 0.9.0, got: $version_output" >&2
  exit 1
fi

echo
echo "== Examples, security, and focused authoring QA =="
run scripts/check_examples.sh
run scripts/qa_security_regressions.sh
run scripts/qa_08_stdlib_v2.sh
run scripts/qa_08_resource_authoring.sh
run scripts/qa_08_unrolling.sh
run scripts/qa_08_resource_pack.sh
run scripts/check_resource_snapshots.sh
run scripts/check_resource_schemas.sh

echo
echo "== 0.9 tooling and stdlib-v3 matrix =="
work_dir="$(mktemp -d "${TMPDIR:-/tmp}/cobble-qa-09-release.XXXXXX")"
cleanup() {
  if [[ "${COBBLE_QA_KEEP:-}" == "1" ]]; then
    echo "Keeping QA work directory: $work_dir"
  else
    rm -rf "$work_dir"
  fi
}
trap cleanup EXIT

stdlib_v3_source="$work_dir/stdlib_v3.cbl"
cat >"$stdlib_v3_source" <<'CBL'
from stdlib import datapack, entity, item_component, position, selector, storage, text

datapack.item_modifier("items/reward_components", {
    "function": "minecraft:set_components",
    "components": item_component.components(
        item_component.custom_name(text.colored("Cobble Reward", "gold")),
        item_component.lore([text.plain("Generated by Cobble")]),
        item_component.unbreakable()
    )
})

def main():
    storage.set(storage.path("players", "current"), "alex")
    storage.get(storage.index("players.events", 0))
    entity.teleport(selector.current(), position.relative(0, 1, 0))
CBL

run cargo run --locked --quiet -- build "$stdlib_v3_source" --namespace qa09 -o "$work_dir/stdlib-v3"
inspect_json="$work_dir/stdlib-v3.inspect.json"
echo "+ cargo run --locked --quiet -- inspect $work_dir/stdlib-v3 --json"
cargo run --locked --quiet -- inspect "$work_dir/stdlib-v3" --json >"$inspect_json"
assert_json_field \
  "inspect schema" \
  "$inspect_json" \
  'data["schema_version"] == 1 and data["ok"] is True and data["status"] == "ok"'
assert_json_field \
  "stdlib-v3 item modifier resource" \
  "$inspect_json" \
  'any(resource["kind"] == "item_modifier" and resource["path"] == "items/reward_components" for resource in data["manifest"]["resources"])'

check_json="$work_dir/check.plugins.json"
echo "+ cargo run --locked --quiet -- check examples/26_smoke --json --symbols --experimental-plugins --experimental-python-compat"
cargo run --locked --quiet -- check examples/26_smoke --json --symbols --experimental-plugins --experimental-python-compat >"$check_json"
assert_json_field \
  "check schema and experimental tooling skeletons" \
  "$check_json" \
  'data["schema_version"] == 1 and data["ok"] is True and data["experimental_plugins"]["enabled"] is True and data["experimental_python_compat"]["enabled"] is True and data["experimental_python_compat"]["mode"] == "diagnostics-only"'

plugin_project="$work_dir/plugin-project"
mkdir -p "$plugin_project/src" "$plugin_project/plugins"
cat >"$plugin_project/cobble.toml" <<'TOML'
[project]
name = "qa09_plugins"
description = "QA 0.9 plugin manifest fixture"
namespace = "qa09_plugins"
version = "1.0.0"
pack_format = "101.1"

[build]
source = "src"
output = "output"
entry_points = []
TOML
cat >"$plugin_project/src/main.cbl" <<'CBL'
def main():
    /say plugin manifest
CBL
cat >"$plugin_project/plugins/example_lints.toml" <<'TOML'
plugin_version = 1
name = "example_lints"
kind = "diagnostics"

[capabilities]
read_project_metadata = true
read_source_text = true
emit_diagnostics = true
TOML
plugin_manifest_json="$work_dir/check.plugin-manifest.json"
echo "+ cargo run --locked --quiet -- check $plugin_project --json --experimental-plugins"
cargo run --locked --quiet -- check "$plugin_project" --json --experimental-plugins >"$plugin_manifest_json"
assert_json_field \
  "plugin manifest draft schema" \
  "$plugin_manifest_json" \
  'data["schema_version"] == 1 and data["ok"] is True and data["experimental_plugins"]["manifests_checked"] == 1 and data["experimental_plugins"]["manifests"][0]["name"] == "example_lints" and "emit_diagnostics" in data["experimental_plugins"]["manifests"][0]["capabilities"]'

migrate_json="$work_dir/migrate.json"
echo "+ cargo run --locked --quiet -- migrate examples/resource_pack --json"
cargo run --locked --quiet -- migrate examples/resource_pack --json >"$migrate_json"
assert_json_field \
  "migrate schema" \
  "$migrate_json" \
  'data["schema_version"] == 1 and data["ok"] is True and data["from"] == "0.8" and data["to"] == "0.9" and data["changed"] is False and data["config"]["experimental_resource_pack"] is True and data["config"]["experimental_python_compat"] is False'

echo
echo "== 0.9 validated build matrix =="
run cargo run --locked -- build examples/stdlib_v2 --validate -o "$work_dir/stdlib-v2"
run cargo run --locked -- build examples/stdlib_v3 --validate -o "$work_dir/stdlib-v3-example"
run cargo run --locked -- build examples/resource_authoring --validate -o "$work_dir/resource-authoring"
run cargo run --locked -- build examples/unrolling --validate -o "$work_dir/unrolling"
run cargo run --locked -- build examples/resource_pack --experimental-resource-pack --validate -o "$work_dir/resource-pack"
run cargo run --locked -- inspect "$work_dir/stdlib-v2" --json
run cargo run --locked -- inspect "$work_dir/stdlib-v3-example" --json
run cargo run --locked -- inspect "$work_dir/resource-authoring" --json
run cargo run --locked -- inspect "$work_dir/unrolling" --json
run cargo run --locked -- inspect "$work_dir/resource-pack" --json

echo
echo "== Web gate =="
(
  cd web
  run npm run test:web
)

echo
echo "== Optional Minecraft server gate =="
if [[ "${COBBLE_MINECRAFT_EULA_ACCEPTED:-}" == "1" ]]; then
  run scripts/test_minecraft_server.sh
else
  echo "Skipping Minecraft server gate; set COBBLE_MINECRAFT_EULA_ACCEPTED=1 after accepting the Minecraft EULA to include it."
fi

echo
echo "== Package dry-runs =="
run cargo package "${package_args[@]}"
run cargo publish --dry-run "${package_args[@]}"
package_version="$(cargo metadata --locked --no-deps --format-version 1 | python3 -c 'import json,sys; data=json.load(sys.stdin); print(data["packages"][0]["version"])')"
if [[ "$package_version" != "0.9.0" ]]; then
  echo "Expected package metadata version 0.9.0, got: $package_version" >&2
  exit 1
fi

echo
echo "0.9.0 release QA gate passed"
